apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-node-info
  namespace: client-library
  labels:
    app: deployment-node-info
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-node-info
  template:
    metadata:
      labels:
        app: deployment-node-info
    spec:
      volumes:
      - name: client-library-data
        persistentVolumeClaim:
          claimName: clientlibraryclaim
      containers:
      - name: nodeinfo
        image: sangwondockerhub/node_info
        command: ["sh","-c"]
        args: ["python Node_Info.py > /client-resource/Node_Info.json"]
        volumeMounts:
        - name: client-library-data
          mountPath: /client-resource
    