apiVersion: v1
kind: Pod
metadata:
  name: podlist2
  namespace: sangwon
  labels:
    app: sangwon-test
spec:
  volumes:
  - name: shared-data
    persistentVolumeClaim:
      claimName: myclaim
  containers:
  - name: nginx2
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /app-data
  restartPolicy: Never
  