apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-pod-list
  namespace: client-library
  labels:
    app: deployment-pod-list
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-pod-list
  template:
    metadata:
      labels:
        app: deployment-pod-list
    spec:
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: clientlibraryclaim
      containers:
      - name: podlist
        image: sangwondockerhub/pod_list
        command: ["sh","-c"]
        args: ["python pod_list.py > /client-resource/Pod_list.json"]
        volumeMounts:
        - name: shared-data
          mountPath: /client-resource
    