apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clientlibraryclaim
  namespace: client-library
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
