apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.firstpage }}
  #namespace: {{ .Values.frontendns }}
  labels:
    app: {{ .Values.firstpage }}
spec:
<<<<<<< HEAD
  replicas: {{ .Values.replicas }}
=======
  replicas: 3
>>>>>>> dd18ce3ad1461e55d10a1e39f477deec412c40a6
  selector:
    matchLabels:
      app: {{ .Values.firstpage }}
  template:
    metadata:
      labels:
        app: {{ .Values.firstpage }}
    spec:
      volumes:
      - name: {{ .Values.volumename }}
        persistentVolumeClaim:
          claimName: {{ .Values.volumeclaimName }}
      containers:
      - name: {{ .Values.firstpage }}
        image: {{ .Values.frontendimage }}
        volumeMounts:
        - name: {{ .Values.volumename }}
          mountPath: {{ .Values.mountPath }}
