---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: kubeboard
  region: ap-northeast-1
  version: "1.20"
availabilityZones: [" "]
managedNodeGroups:
- name: node-group
  desiredCapacity: 1
  instanceType: t3.medium
  